---
apiVersion: v1
kind: Service
metadata:
  name: alb6443-test-redis-service
  labels:
    username: alb6443
    env: test
spec:
  type: ClusterIP
  selector:
    app: alb6443-test-redis-deployment
  ports:
  - name: alb6443-test-redis-deployment
    port: 6379
    targetPort: 6379
