---
apiVersion: v1
kind: Service
metadata:
  name: alb6443-test-flask-service
  labels:
    username: alb6443
    env: test
spec:
  type: ClusterIP
  selector:
    app: alb6443-test-flask-app
  ports:
  - name: alb6443-test-flask-app
    port: 5000
    targetPort: 5000
